=== plappermaul/broadcom-switches/sdk-6.5.7/src/appl/diag/dcmn/db/jericho_2/dbal/fields/fields_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           elementFormDefault="qualified">

<xs:include schemaLocation="../dbal_types_definition.xsd"/>        

    <xs:element name="FieldDbCatalog">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="Field" maxOccurs="unbounded">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="OneLineDescription" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="FieldDbInterface"  minOccurs="1" maxOccurs="1">
            <xs:complexType>
            <xs:sequence>
                <xs:element name="FieldLabels" type="LabelListType" minOccurs="1" maxOccurs="1"/>
                <xs:element name="DefaultValue" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                <xs:choice>
                    <xs:element name="ChildFields" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ChildField" minOccurs="1" maxOccurs="5"> <!-- maxOccurs = DBAL_FIELD_MAX_CHILDS_PER_FIELD -->
                        <xs:complexType>
                            <xs:attributeGroup ref="NameAttr"/>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    </xs:complexType>
                    </xs:element>
                    <xs:element name="EnumValues" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="EnumVal" minOccurs="1" maxOccurs="31"> <!-- maxOccurs = DBAL_FIELD_MAX_NUM_OF_ENUM_VALUES -->
                        <xs:complexType>
                            <xs:attributeGroup ref="EnumValsAttr"/>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    </xs:complexType>
                    </xs:element>
                </xs:choice>
            </xs:sequence>
                <xs:attributeGroup ref="FieldTypeAttr"/>
            </xs:complexType>
            </xs:element>
            <xs:element name="FieldToPhyDbMapping"  minOccurs="1" maxOccurs="1">
            <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element name="ChildFieldsEncoding" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ChildField" minOccurs="1" maxOccurs="5"> <!-- maxOccurs = DBAL_FIELD_MAX_CHILDS_PER_FIELD -->
                        <xs:complexType>
                            <xs:attributeGroup ref="NameAttr"/>
                            <xs:attributeGroup ref="FieldEncodeAttr"/>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    </xs:complexType>
                    </xs:element>
                    <xs:element name="EnumValueMapping" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="EnumVal" minOccurs="1" maxOccurs="31"> <!-- maxOccurs = DBAL_FIELD_MAX_NUM_OF_ENUM_VALUES -->
                        <xs:complexType>
                            <xs:attributeGroup ref="EnumMappingAttr"/>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    </xs:complexType>
                    </xs:element>
                </xs:choice>
                <xs:element name="Encoding" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:attributeGroup ref="FieldEncodeAttr"/>
                </xs:complexType>
                </xs:element>
                <xs:element name="MaxValue" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            </xs:complexType>
            </xs:element>
        </xs:sequence>
            <xs:attributeGroup ref="FieldDefinitionAttr"/>
        </xs:complexType>

            <!-- In Field, all child encoding should be defined in interface and vice-versa -->
            <xs:keyref name="MappingChildKeyRef" refer="MappedChild">
                <xs:selector xpath="FieldToPhyDbMapping/ChildFieldsEncoding/ChildField" />
                <xs:field xpath="@Name" />
            </xs:keyref>

            <xs:key name="MappedChild">
                <xs:selector xpath="FieldDbInterface/ChildFields/ChildField" />
                <xs:field xpath="@Name" />
            </xs:key>
            
            <xs:keyref name="ChildListKeyRef" refer="ChildList">
                <xs:selector xpath="FieldDbInterface/ChildFields/ChildField" />
                <xs:field xpath="@Name" />
            </xs:keyref>

            <xs:key name="ChildList">
                <xs:selector xpath="FieldToPhyDbMapping/ChildFieldsEncoding/ChildField" />
                <xs:field xpath="@Name" />
            </xs:key>
            
            <xs:unique name="UniqueChildField">
                <xs:selector xpath="FieldDbInterface/ChildFields/ChildField"/>
                <xs:field xpath="@Name"/>
            </xs:unique>

            <xs:unique name="UniqueChildEncoded">
                <xs:selector xpath="FieldToPhyDbMapping/ChildFieldsEncoding/ChildField"/>
                <xs:field xpath="@Name"/>
            </xs:unique>

            <!-- In Field, all enum mapping should be defined in interfacea nd vice-versa -->
            <xs:keyref name="MappingEnumKeyRef" refer="MappedEnum">
                <xs:selector xpath="FieldToPhyDbMapping/EnumValueMapping/EnumVal" />
                <xs:field xpath="@Name" />
            </xs:keyref>

            <xs:key name="MappedEnum">
                <xs:selector xpath="FieldDbInterface/EnumValues/EnumVal" />
                <xs:field xpath="@Name" />
            </xs:key>

            <xs:keyref name="EnumValsKeyRef" refer="EnumVals">
                <xs:selector xpath="FieldDbInterface/EnumValues/EnumVal" />
                <xs:field xpath="@Name" />
            </xs:keyref>

            <xs:key name="EnumVals">
                <xs:selector xpath="FieldToPhyDbMapping/EnumValueMapping/EnumVal" />
                <xs:field xpath="@Name" />
            </xs:key>
            
            <xs:unique name="UniqueEnumVal">
                <xs:selector xpath="FieldDbInterface/EnumValues/EnumVal"/>
                <xs:field xpath="@Name"/>
            </xs:unique>

            <xs:unique name="UniqueEnumMapping">
                <xs:selector xpath="FieldToPhyDbMapping/EnumValueMapping/EnumVal"/>
                <xs:field xpath="@Name"/>
            </xs:unique>

            </xs:element>
    </xs:sequence>
    </xs:complexType>
                
        <xs:unique name="UniqueField">
            <xs:selector xpath="Field"/>
            <xs:field xpath="@Name"/>
        </xs:unique>
                    
    </xs:element>

</xs:schema>

=== plappermaul/broadcom-switches/sdk-6.5.7/src/appl/diag/dcmn/db/jericho_2/dbal/fields/pemla_fields.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    ******************************************************
    DBAL Fields DB:
    This xml contains the fields DB for the DBAL.
    The data is loaded to the device during init process
    ******************************************************

    DB Rules:
    *********
-->

<FieldDbCatalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fields_schema.xsd">

    <Field Name="PEMLA_TPID_1" Size="16">
        <OneLineDescription>TPID Value used to identify Etherent Tags. If matched, Qualifier is set to 1</OneLineDescription>
        <FieldDbInterface Type="UINT32">
            <FieldLabels>L2</FieldLabels>
        </FieldDbInterface>
        <FieldToPhyDbMapping>
        </FieldToPhyDbMapping>
    </Field>

    <Field Name="PEMLA_TPID_2" Size="16">
        <OneLineDescription>TPID Value used to identify Etherent Tags. If matched, Qualifier is set to 2</OneLineDescription>
        <FieldDbInterface Type="UINT32">
            <FieldLabels>L2</FieldLabels>
        </FieldDbInterface>
        <FieldToPhyDbMapping>
        </FieldToPhyDbMapping>
    </Field>

    <Field Name="PEMLA_TPID_3" Size="16">
        <OneLineDescription>TPID Value used to identify Etherent Tags. If matched, Qualifier is set to 3</OneLineDescription>
        <FieldDbInterface Type="UINT32">
            <FieldLabels>L2</FieldLabels>
        </FieldDbInterface>
        <FieldToPhyDbMapping>
        </FieldToPhyDbMapping>
    </Field>

    <Field Name="PEMLA_TPID_4" Size="16">
        <OneLineDescription>TPID Value used to identify Etherent Tags. If matched, Qualifier is set to 4</OneLineDescription>
        <FieldDbInterface Type="UINT32">
            <FieldLabels>L2</FieldLabels>
        </FieldDbInterface>
        <FieldToPhyDbMapping>
        </FieldToPhyDbMapping>
    </Field>

    <Field Name="PEMLA_TPID_5" Size="16">
        <OneLineDescription>TPID Value used to identify Etherent Tags. If matched, Qualifier is set to 5</OneLineDescription>
        <FieldDbInterface Type="UINT32">
            <FieldLabels>L2</FieldLabels>
        </FieldDbInterface>
        <FieldToPhyDbMapping>
        </FieldToPhyDbMapping>
    </Field>

    <Field Name="PEMLA_TPID_6" Size="16">
        <OneLineDescription>TPID Value used to identify Etherent Tags. If matched, Qualifier is set to 6</OneLineDescription>
        <FieldDbInterface Type="UINT32">
            <FieldLabels>L2</FieldLabels>
        </FieldDbInterface>
        <FieldToPhyDbMapping>
        </FieldToPhyDbMapping>
    </Field>

    <Field Name="PEMLA_TPID_7" Size="16">
        <OneLineDescription>TPID Value used to identify Etherent Tags. If matched, Qualifier is set to 7</OneLineDescription>
        <FieldDbInterface Type="UINT32">
            <FieldLabels>L2</FieldLabels>
        </FieldDbInterface>
        <FieldToPhyDbMapping>
        </FieldToPhyDbMapping>
    </Field>

</FieldDbCatalog>

=== plappermaul/broadcom-switches/sdk-6.5.7/src/appl/diag/dcmn/db/jericho_2/dbal/validation_test/fields/fields_validation_test.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

-->

<FieldDbCatalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="../../fields/fields_schema.xsd">

    <Field Name="IPV4" Size="32">
		<OneLineDescription>blabla</OneLineDescription>
		<FieldDbInterface Type="IP">
            <FieldLabels>L3 L2</FieldLabels>
        </FieldDbInterface>
        <FieldToPhyDbMapping>
        </FieldToPhyDbMapping>
    </Field>

    <Field Name="VRF" Size="DNX_DATA.module_testing.dbal.vrf_field_size">
        <OneLineDescription></OneLineDescription>
        <FieldDbInterface Type="UINT32">
            <FieldLabels>L3</FieldLabels>
        </FieldDbInterface>
        <FieldToPhyDbMapping>
	        <Encoding EncodeType="HARD_VALUE" Value="-8"/>
        </FieldToPhyDbMapping>
    </Field>

    <Field Name="IPV6" Size="128">
        <OneLineDescription></OneLineDescription>
        <FieldDbInterface Type="ARRAY8">
            <FieldLabels>L3 MPLS</FieldLabels>
	        <DefaultValue>15</DefaultValue>
        </FieldDbInterface>
        <FieldToPhyDbMapping>
        </FieldToPhyDbMapping>
    </Field>

    <Field Name="CORE_ID" Size="1">
        <OneLineDescription></OneLineDescription>
        <FieldDbInterface Type="BOOL">
            <FieldLabels>L2 L3 MPLS</FieldLabels>
	        <DefaultValue>-1</DefaultValue>
        </FieldDbInterface>
        <FieldToPhyDbMapping>
        </FieldToPhyDbMapping>
    </Field>

    <Field Name="C_VLAN" Size="4">
        <OneLineDescription></OneLineDescription>
        <FieldDbInterface Type="ENUM"> <!-- printing yype -->
            <FieldLabels>L2</FieldLabels>
            <EnumValues>   <!-- create the Enum -->
                <EnumVal Name="DEFAULT" Description="default value of field"/>
                <EnumVal Name="DROP" Description="drop action description"/>
                <EnumVal Name="SNOOP" Description="snoop action description"/>
                <EnumVal Name="REDIRECT" Description="redirect action description"/>
            </EnumValues>
        </FieldDbInterface>
        <FieldToPhyDbMapping>
            <EnumValueMapping>  <!-- create the mapping table (function) -->
                <EnumVal Name="DEFAULT" Value="0"/>
                <EnumVal Name="DROP" Value="5"/>
                <EnumVal Name="REDIRECT" Value="3"/>
                <EnumVal Name="SNOOP" Value="14"/>
            </EnumValueMapping>
        </FieldToPhyDbMapping>
    </Field>

</FieldDbCatalog>
