=== plappermaul/broadcom-switches/sdk-6.5.7/src/appl/diag/dcmn/db/jericho_2/dbal/tables_pemla/pemla_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           elementFormDefault="qualified"
           >

<xs:include schemaLocation="../dbal_types_definition.xsd"/>        

    <xs:element name="AppDbCatalog">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="AppDB" maxOccurs="unbounded">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="OneLineDescription" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="MaturityLevel" minOccurs="0" maxOccurs="1">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="2"/>
                </xs:restriction>
            </xs:simpleType>
            </xs:element>
            <!-- Interface -->
            <xs:element name="AppDbInterface" type="TableInterfaceType" minOccurs="1" maxOccurs="1"/>
            
            <!-- Physical Mapping -->
            <xs:element name="AppToPhyDbMapping" minOccurs="1" maxOccurs="1">
            <xs:complexType>
            <xs:sequence>
                <xs:element name="CoreMode" type="CroeModeType" minOccurs="1" maxOccurs="1"/>
                <xs:element name="DbId" type="xs:integer" minOccurs="1" maxOccurs="1"/>
                <xs:element name="FieldMapping" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                <xs:sequence>
                    <xs:element name="Field" minOccurs="1" maxOccurs="70">
                    <xs:complexType>
                        <xs:attributeGroup ref="PemlaFieldMappingAttr" />
                    </xs:complexType>
                    </xs:element>
                </xs:sequence>
                </xs:complexType>
                </xs:element>
            </xs:sequence>
            </xs:complexType>
            </xs:element>
        </xs:sequence>
            <xs:attributeGroup ref="TableDefinitionAttr"/>
        </xs:complexType>
        </xs:element>
    </xs:sequence>
    </xs:complexType>
    
        <!-- In AppDBCatalog, AppDB names are unique -->
        <xs:unique name="UniqueAppDBName">
            <xs:selector xpath="AppDB" />
            <xs:field xpath="@Name" />
        </xs:unique>
        
    </xs:element>
    
</xs:schema>

=== plappermaul/broadcom-switches/sdk-6.5.7/src/appl/diag/dcmn/db/jericho_2/dbal/tables_pemla/pemla_definition.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    ******************************************************
    DBAL MDB Logical Tables:
    This xml contains the MDB logical DB for the DBAL.
    The data is loaded to the device during init process
    ******************************************************

    Aligned to Arch version: 
    //depot2/Jericho2/A0/docs/ARCH-specs/Packet-Processing/Datapath_program/Standard_1/JR2.Standard_1.MDB_AppDBs_compiled.xml
    #48
-->

<AppDbCatalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="pemla_schema.xsd">

    <AppDB Name="PEMLA_PARSER_TPID">
        <OneLineDescription>switch tpid pemla table</OneLineDescription>
        <MaturityLevel>1</MaturityLevel>
        <AppDbInterface Type="DIRECT">
            <Key>
            </Key>
            <Result>
                <Field Name="PEMLA_TPID_1"/>
                <Field Name="PEMLA_TPID_2"/>
                <Field Name="PEMLA_TPID_3"/>
                <Field Name="PEMLA_TPID_4"/>
                <Field Name="PEMLA_TPID_5"/>
                <Field Name="PEMLA_TPID_6"/>
                <Field Name="PEMLA_TPID_7"/>
            </Result>
            <TableLabels>L2</TableLabels>
        </AppDbInterface>
        <AppToPhyDbMapping> 
            <CoreMode Mode="SBC"/>
            <DbId>7</DbId>
            <FieldMapping>
                <Field Name="PEMLA_TPID_1" HwValue="0"/>
                <Field Name="PEMLA_TPID_2" HwValue="1"/>
                <Field Name="PEMLA_TPID_3" HwValue="2"/>
                <Field Name="PEMLA_TPID_4" HwValue="3"/>
                <Field Name="PEMLA_TPID_5" HwValue="4"/>
                <Field Name="PEMLA_TPID_6" HwValue="5"/>
                <Field Name="PEMLA_TPID_7" HwValue="6"/>
            </FieldMapping>
        </AppToPhyDbMapping>
    </AppDB>
    
</AppDbCatalog>
